---
title: "Lab 02: Data Visualization"
subtitle: ""
author: "Group member names here"
date: "due September 13, 11:59 PM"
output: 
  html_document:
    toc: true
    toc_float: true
    number_section: false
    highlight: tango
    theme: "cosmo"
link-citations: yes
editor_options: 
  chunk_output_type: console
---

# Load Packages

```{r load-packages, message = FALSE, warning = FALSE}
library(tidyverse) 
library(viridis)
library(ggridges)
``` 

# Load Data
```{r load-data, message = F}
anes <- read_csv("data/anes2020_subset.csv")
```

# Exercise 1


# Exercise 2

```{r ex-2}

```

# Exercise 3


```{r ex-3}

```

# Exercise 4

```{r ex-4}

```

# Exercise 5

```{r ex-5}

```

# Exercise 6

Those who hunt and fish tend to be more politically conservative.

```{r ex-6}

```

# Exercise 7

```{r ex-7}

```

# Exercise 8


# Exercise 9

```{r ex-9, message = FALSE, warning = FALSE}

```

# Exercise 10

```{r ex-10}
set.seed(18)
anes2 <- anes %>%
  sample_frac(.10)
```

# Exercise 11

```{r ex-11}

```

# Exercise 12


